package com.alipay.merchant.common.dal.auto.daointerface;

import com.alipay.merchant.common.dal.auto.dataobject.MerchantInfoDO;
import com.alipay.merchant.common.dal.auto.dataobject.MerchantInfoDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    long countByExample(MerchantInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int deleteByExample(MerchantInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int deleteByPrimaryKey(String merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int insert(MerchantInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int insertSelective(MerchantInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    List<MerchantInfoDO> selectByExample(MerchantInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    MerchantInfoDO selectByPrimaryKey(String merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int updateByExampleSelective(@Param("row") MerchantInfoDO row, @Param("example") MerchantInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int updateByExample(@Param("row") MerchantInfoDO row, @Param("example") MerchantInfoDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int updateByPrimaryKeySelective(MerchantInfoDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_info
     *
     * @mbg.generated Sun Apr 26 21:19:18 AEST 2026
     */
    int updateByPrimaryKey(MerchantInfoDO row);
}