package com.alipay.merchant.common.dal.auto.dataobject;

import java.util.Date;

public class MerchantInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.merchant_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.merchant_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.merchant_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String merchantCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.merchant_id
     *
     * @return the value of merchant_info.merchant_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.merchant_id
     *
     * @param merchantId the value for merchant_info.merchant_id
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.merchant_name
     *
     * @return the value of merchant_info.merchant_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.merchant_name
     *
     * @param merchantName the value for merchant_info.merchant_name
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.merchant_category
     *
     * @return the value of merchant_info.merchant_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getMerchantCategory() {
        return merchantCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.merchant_category
     *
     * @param merchantCategory the value for merchant_info.merchant_category
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setMerchantCategory(String merchantCategory) {
        this.merchantCategory = merchantCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.status
     *
     * @return the value of merchant_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.status
     *
     * @param status the value for merchant_info.status
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.created_at
     *
     * @return the value of merchant_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.created_at
     *
     * @param createdAt the value for merchant_info.created_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_info.updated_at
     *
     * @return the value of merchant_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_info.updated_at
     *
     * @param updatedAt the value for merchant_info.updated_at
     *
     * @mbg.generated Mon May 04 15:02:00 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}